name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      # Required for trusted publishing
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify desired Python version, e.g., '3.11'

      - name: Install uv
        run: |
          pip install uv==0.4.18  # Pin to a specific version for reproducibility

      - name: Create and activate virtual environment
        run: |
          uv venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo ".venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Build package
        run: |
          uv run python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      # Required for trusted publishing
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/simple-mcp-client  # Replace YOURPROJECT with your actual project name
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
